allowBuilds:
  '0': u
  '1': n
  '2': r
  '3': s
  '4': '-'
  '5': r
  '6': e
  '7': s
  '8': o
  '9': l
  '10': v
  '11': e
  '12': r
  '13': =
  '14': t
  '15': r
  '16': u
  '17': e
  sharp: false
  unrs-resolver: false
